//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoanDetail
    {
        public int Loan_ID { get; set; }
        [Required(ErrorMessage = "Enter Amount")]
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Interest { get; set; }
        [Required(ErrorMessage = "Enter Tenure")]
        public Nullable<double> Tenure { get; set; }
        [Display(Name = "Loan Account Number")]
        public string Loan_Account_Number { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> Application_ID { get; set; }
    
        public virtual User_Detail User_Detail { get; set; }
    }
}
