//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Property
    {
        public int Property_ID { get; set; }
        [Required(ErrorMessage = "Enter your Plot Number")]
        [Display(Name = "Plot Number")]
        public string Plot_Number { get; set; }
        [Required(ErrorMessage = "Enter your Plot Area")]
        [Display(Name = "Plot Area")]
        public string Property_Area { get; set; }
        [Required(ErrorMessage = "Enter Pincode")]
        public string Pincode { get; set; }
        [Required(ErrorMessage = "Select the property type")]
        [Display(Name = "Plot Type")]
        public string Type_Of_Property { get; set; }
        [Required(ErrorMessage = "Enter your Estimated cost")]
        [Display(Name = "Estimated Cost")]
        public Nullable<double> Estimated_Cost { get; set; }
        public Nullable<int> Application_ID { get; set; }
    
        public virtual User_Detail User_Detail { get; set; }
    }
}
