//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Status
    {
        public int Status_ID { get; set; }

        [Display(Name = "Loan Status")]
        public string Loan_Status { get; set; }
 
        [Display(Name = "Verification Status")]
        public string Verification_Status { get; set; }
        public Nullable<int> Application_ID { get; set; }
    
        public virtual User_Detail User_Detail { get; set; }
    }
}
