//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Upload_Document
    {
        public int Document_ID { get; set; }
        [Required]
        [Display(Name = "PAN Card")]
        public string Pan_Card { get; set; }
        [Required]
        [Display(Name = "Aadhar Card")]
        public string Aadhar_Card { get; set; }
        [Required]
        [Display(Name = "Salary Slip")]
        public string Salary_Slip { get; set; }
        [Required]
        public string LOA { get; set; }
        [Required]
        public string NOC { get; set; }
        [Required]
        public string Agreement { get; set; }
        public Nullable<int> Application_ID { get; set; }
    
        public virtual User_Detail User_Detail { get; set; }
    }
}
